source 'https://rubygems.org'

gem 'rake'
gem 'lino'
gem 'nokogiri'
gem 'rake_dependencies'
gem 'rake_terraform'
gem 'rake_docker'
gem 'rake_fly'
gem 'rake_ssh'
gem 'confidante'
gem 'docker-api'
gem 'semantic'
gem 'dotenv'
gem 'activesupport'
