---
region: "eu-west-2"
component: "consul-example"

private_network_cidr: "10.0.0.0/16"

state_bucket_name: "infrablocks-%{hiera('component')}-%{hiera('deployment_identifier')}"
secrets_bucket_name: "%{hiera('state_bucket_name')}"

domain_state_key: "domain/deployments/%{hiera('deployment_identifier')}.tfstate"
domain_state_bucket_name: "%{hiera('state_bucket_name')}"
domain_state_bucket_region: "%{hiera('region')}"
domain_state_bucket_is_encrypted: "true"

network_state_key: "network/deployments/%{hiera('deployment_identifier')}.tfstate"
network_state_bucket_name: "%{hiera('state_bucket_name')}"
network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_is_encrypted: "true"

service_discovery_cluster_state_key: "service_discovery_cluster/deployments/%{hiera('deployment_identifier')}.tfstate"
service_discovery_cluster_state_bucket_name: "%{hiera('state_bucket_name')}"
service_discovery_cluster_state_bucket_region: "%{hiera('region')}"
service_discovery_cluster_state_bucket_is_encrypted: "true"

application_cluster_state_key: "application_cluster/deployments/%{hiera('deployment_identifier')}.tfstate"
application_cluster_state_bucket_name: "%{hiera('state_bucket_name')}"
application_cluster_state_bucket_region: "%{hiera('region')}"
application_cluster_state_bucket_is_encrypted: "true"

consul_servers_state_key: "consul-services/deployments/%{hiera('deployment_identifier')}.tfstate"
consul_servers_state_bucket_name: "%{hiera('state_bucket_name')}"
consul_servers_state_bucket_region: "%{hiera('region')}"
consul_servers_state_bucket_is_encrypted: "true"

consul_agents_state_key: "consul-agents/deployments/%{hiera('deployment_identifier')}.tfstate"
consul_agents_state_bucket_name: "%{hiera('state_bucket_name')}"
consul_agents_state_bucket_region: "%{hiera('region')}"
consul_agents_state_bucket_is_encrypted: "true"
